-- Oracle PL/SQL
SELECT HOUR, COUNT(A.DATETIME)
    FROM (SELECT LEVEL -1 AS HOUR FROM DUAL CONNECT BY LEVEL <= 24) L
    LEFT JOIN ANIMAL_OUTS A
    ON L.HOUR = TO_CHAR(A.DATETIME, 'HH24')
    GROUP BY HOUR
    ORDER BY HOUR;
